# Generated by Django 5.0.7 on 2024-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.TextField(blank=True, null=True)),
                ('char_guild', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('item_location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'char_inventory',
                'managed': False,
            },
        ),
    ]
